[package]
name = "frames"
version = "1.0.0"
edition = "2021"

[dependencies]
futures = { version = "0.3.27", optional = true }
serialport = { version = "4.3.0", optional = true }

[features]
serialport = ["dep:serialport"]
